version: "3.7"

services:
  # Backend server (Django)
  django:
    volumes:
      - .:/app
    command: "gunicorn --chdir ./papers_versus_people/ --bind :5100 --reload --workers 2 papers_versus_people.wsgi"
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:12.7
    ports:
      - "5432:5432"
    restart: "always"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_db:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
  frontend:
