# Generated by Django 4.1.7 on 2023-05-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(default="admin", max_length=200),
            preserve_default=False,
        ),
    ]
