# Generated by Django 4.1.7 on 2023-05-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_cardset_official_alter_card_text"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winning_match",
                to="matches.playerinmatch",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winning_score",
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="playerinmatch",
            name="played_card",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="played_by_player",
                to="cards.card",
            ),
        ),
        migrations.AddField(
            model_name="playerinmatch",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="match",
            name="current_black_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cards.card"
            ),
        ),
    ]
