# Generated by Django 4.1.7 on 2023-05-08 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_match_winner_match_winning_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="max_rounds",
        ),
    ]
