# Generated by Django 4.1.7 on 2023-05-09 22:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0003_remove_match_max_rounds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="czar_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), default=list, size=None
            ),
        ),
    ]
